### ISSUE TITLE
502 Proxy Error when Downloading InGrid iBus Component

### ISSUE THREAD

**Issue by dawidaleksanderwalczak** [informationgrid/informationgrid.github.io#2]
**Description:**
I am experiencing a proxy error when attempting to download the InGrid iBus component from the provided link: https://distributions.informationgrid.eu/ingrid-ibus/.

**Steps to Reproduce:**
Navigate to https://distributions.informationgrid.eu/ingrid-ibus/
Attempt to download the iBus component

**Expected Behavior:**
The download should start successfully.

**Actual Behavior:**
The following error message is displayed:
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request.

Reason: Error reading from remote server

Apache/2.4.52 (Ubuntu) Server at distributions.informationgrid.eu Port 443
```
**Additional Context:**
This issue is blocking the download of the essential iBus component needed for setting up the InGrid environment.

Please look into this issue at your earliest convenience. Thank you!

**Comment by joachimmueller** [comment]
Hi Dawid, 

thanks for pointing this out. I fixed the problem just now. An underlying webserver was not startet.

Best Regards
Joachim
